spring:
  main:
    web-application-type: reactive

  cloud:
    gateway:
      routes:
        - id: task-service
          uri: http://localhost:8081
          predicates:
            - Path=/tasks/**
        - id: user-service
          uri: http://localhost:8083
          predicates:
            - Path=/users/**